### ISSUE TITLE
Document using Zeebe Helm Charts together with Prometheus to collect metrics

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-helm#2]
Every Zeebe broker provides metrics that can easily be collected by Prometheus, so that you can aggregate all metrics across brokers in a cluster or use Grafana to visualize it.

An example can be found in this project, where I use Prometheus Helm charts to install the Prometheus Operator: https://github.com/berndruecker/kafka-connect-zeebe-benchmark/blob/master/kubernetes/setup-cluster.sh#L13

```
helm install --name metrics stable/prometheus-operator
```

And then install a service monitor for Zeebe, which is the connection between Zeebe and Prometheus: https://github.com/berndruecker/kafka-connect-zeebe-benchmark/blob/master/kubernetes/k8s-service-monitor.yaml

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-monitor
  labels:
      release: metrics
  namespace: default
spec:
  selector:
    matchLabels:
      app: zeebe-zeebe  ###### THIS HAS TO MATCH THE label of the Zeebe Service
  endpoints:
      - honorLabels: true
        port: http
        interval: 10s
```
